name: health_ia_care
description: "An AI-powered healthcare coaching application"
version: 1.0.5+5

environment:
  sdk: ^3.10.4

dependencies:
  auto_validate: ^3.0.8
  bloc: ^9.2.0
  country_flags: ^4.1.2
  dio: ^5.9.2
  equatable: ^2.0.8
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  flutter_onnxruntime: ^1.7.1
  image: ^4.3.0
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.1
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_secure_storage: ^10.0.0
  fpdart: ^1.2.0
  get_it: ^9.2.0
  get_storage: ^2.1.1
  go_router: ^17.2.2
  google_fonts: ^8.1.0
  hydrated_bloc: ^11.0.0
  image_picker: ^1.2.2
  intl: ^0.20.2
  language_code: ^0.7.1
  logging: ^1.3.0
  material_symbols_icons: ^4.2928.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.5
  timeago: ^3.7.1
  video_player: ^2.11.1
  visibility_detector: ^0.4.0+2
  zo_animated_border: ^1.0.7
  sqflite: ^2.3.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/ml/
    - assets/db/ 
    
